# Generated by Django 3.2.3 on 2021-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210515_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
